services:
  api:
    volumes:
      - ./src:/app/src
    command: uvicorn mesadigital.api.main:app --host 0.0.0.0 --port 8000 --reload --reload-dir /app/src
    environment:
      PYTHONPATH: /app/src
